version: '3.9'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timeseries_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timeseries
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s 
      timeout: 5s
      retries: 5
      start_period: 30s 

  redis:
    image: redis:7-alpine
    container_name: timeseries_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: timeseries_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy 
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: timeseries
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
  redis_data: